#!/bin/bash

echo "=== 📱 APK 크래시 로그 확인 ==="
echo ""
echo "1. ADB로 로그 확인 (실시간):"
echo "   adb logcat | grep -i 'fatal\|crash\|exception\|error'"
echo ""
echo "2. 앱 실행 후 크래시 로그만 확인:"
echo "   adb logcat -c && adb logcat | grep -E 'AndroidRuntime|FATAL|Exception'"
echo ""
echo "3. 특정 패키지 로그만 확인:"
echo "   adb logcat | grep 'com.todo.app'"
echo ""
echo "4. 크래시 스택 트레이스 확인:"
echo "   adb logcat *:E"
echo ""
echo "5. 앱 설치 및 실행:"
echo "   adb install -r mobile/android/app/build/outputs/apk/debug/app-debug.apk"
echo "   adb shell am start -n com.todo.app/.MainActivity"
echo ""
echo "=== 로그 파일 저장 ==="
echo "   adb logcat > crash_logs.txt"

